# Generated by Django 6.0.6 on 2026-07-09 23:09

import django.db.models.deletion
import stapel_video.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('join_code', models.CharField(db_index=True, default=stapel_video.models.generate_join_code, max_length=16, unique=True)),
                ('scope_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('scope_trusted', 'Scope-trusted'), ('restricted', 'Restricted')], default='restricted', max_length=16)),
                ('admit_required', models.BooleanField(default=True)),
                ('provider_room_ref', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_video_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('admitted', 'Admitted'), ('denied', 'Denied'), ('left', 'Left')], default='waiting', max_length=10)),
                ('role', models.CharField(choices=[('host', 'Host'), ('guest', 'Guest')], default='guest', max_length=8)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='video.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['joined_at'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['scope_key', 'created_at'], name='video_room_scope_created'),
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['created_by'], name='video_room_creator'),
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['room', 'status'], name='video_participant_room_status'),
        ),
        migrations.AddIndex(
            model_name='roomparticipant',
            index=models.Index(fields=['user'], name='video_participant_user'),
        ),
        migrations.AddConstraint(
            model_name='roomparticipant',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='video_participant_uniq'),
        ),
    ]
